### PR TITLE
Implement Hash for PublicKey.

### PR DESCRIPTION
**Pull request by dpc**
I need HashMap with PublicKey as a key.

### CODE REVIEW

**Comment by apoelstra** [comment]
Hi @dpc! Can you add a unit test that just throws the hashes of a couple thousand public keys into a hsahtable to make sure that none collide? Just as a sanity check.

I'll look into this travis business..

**Comment by dpc** [comment]
Hmm... I thought hashing in Rust is done to u64, so it could potentially collide from time to time, no? Rust `HashMap` would not tell me if there's a collision. As far as I understand, even if all hashes would be 0, only performance would suffer.

**Comment by apoelstra** [comment]
@dpc Yes, it's 64-bits, so you expect a collision after around 2^32 iterations. The probability drops off extremely quickly below that.

**Comment by dpc** [comment]
But how will I detect if there was a collision. AFAIK, HashMap won't tell me.

**Comment by dpc** [comment]
Somethings wrong with travis.

**Comment by apoelstra** [comment]
Test looks good to me. I'll test locally and merge this. Will open a new issue for Travis .. I think something has changed in travis-cargo. Unsure when I'll have a spare moment to investigate.

**Pull request merged**
